name: Code Format

on: [push, pull_request]

jobs:
  check-code-style:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: Check formattting
        run: flutter format --set-exit-if-changed --dry-run .